name: Release
run-name: ${{ github.event.head_commit.message }}

on:
  push:
    tags: v*

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1

      - name: Store wheels
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: wheelhouse/*.whl

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  upload-pypi:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload to TestPyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event.base_ref != 'refs/heads/master'
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event.base_ref == 'refs/heads/master'
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}