name: Tests
on: [push]
jobs:
  Check formatting:
    runs-on: ubuntu-latest

    steps:
      - name: ufmt
        uses: omnilib/ufmt@action-v1
        with:
          path: seqtools
          python-version: "3.11"

  Unit tests:
    runs-on: ubuntu-latest
    needs: Check formatting

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Pytest
        run: pytest --cov=seqtools tests
      
      - name: Coverage
        run: |
          coverage report --fail-under=90
          coverage html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
          retention-days: 2